### ISSUE TITLE
Seahub: cannot import _imaging (PIL)

### ISSUE THREAD

**Issue by vlinevych** [haiwen/seafile-rpi#65]
I've performed the clean installation of 7.1.4 on Raspbian 9 Stretch.
The seahub won't start. After adding `--log-level debug` into `seahub.sh` I've discovered this:

```
Error while loading the application:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.4/seahub/seahub/avatar/models.py", line 23, in <module>
    from PIL import Image
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

I've exported the PYTHONPATH as stated in `seahub.sh` and was able to reproduce it in the interactive shell:

```
export PYTHONPATH=/opt/seafile/seafile-server-7.1.4/seafile/lib/python3.6/site-packages:/opt/seafile/seafile-server-7.1.4/seafile/lib64/python3.6/site-packages:/opt/seafile/seafile-server-7.1.4/seahub:/opt/seafile/seafile-server-7.1.4/seahub/thirdpart:

$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

My local python/python3 do not have PIL or Pillow installed.

**Comment by vlinevych** [comment]
I've found [similar topic](https://forum.seafile.com/t/seahub-failed-to-start-no-module-named-image/12441/2) on the forum, tried to remove pre-installed PIL and Pillow and install them fresh

```
cd /opt/seafile/seafile-server-latest/seahub/thirdpart
mv PIL /tmp
mv Pillow* /tmp
pip3 install -U Pillow -t /opt/seafile/seafile-server-latest/seahub/thirdpart
```
After the installation I've got Pillow-7.2.0.

Unfortunatelly the issue is still there.

**Comment by stfnfrnr** [comment]
> 
Late to the party, however:
I had the exact same issue after upgrading from 7.1.4 to 8.0.7 on Raspbian GNU/Linux 11 and yor steps literally fixed it for me. Thanks a lot!
