### ISSUE TITLE
Seahub does not start after upgrade from 7.0.5 to 7.1.4

### ISSUE THREAD

**Issue by vmario89** [haiwen/seafile-rpi#58]
Hi,
 after spending 2 hours i was able to fix the issue for my self to update 7.0.5. Different errors prevented me having luck. Basically the root cause was that i downloaded  https://github.com/haiwen/seafile-rpi/releases/download/v7.1.4/seafile-server_7.1.4_pi-stretch-stable.tar.gz from releases. I unzipped and run the minor upgrade as usual. After installing and updating the required libs, having python3.5 in my "stretch" raspi, seahub did not start anymore. The error always was 

```
LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.4/seahub/seahub/avatar/models.py", line 23, in <module>
    from PIL import Image
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.4/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/seafile/seafile-server-7.1.4/seahub/thirdpart/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.4/seahub/seahub/avatar/models.py", line 26, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
```

So after messing a lot with PIL, Pillow and python3-pil i decided to upgrade stretch to buster. That gave me python3.7 and more up to date packages. But the error did not change after giving another try

finally i managed to find out the issue.

you have to remove the folder "/seafile-server-7.1.4/seahub/thirdpart/PIL"

I also had to remove "/seafile-server-7.1.4/seahub/thirdpart/Crypto" because it gave me another stack trace with cause Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-37m-arm-linux-gnueabihf.so'".

after deletion of those 2 dirs seahub works now

maybe there should be some documentation hint in the official docs.

regards, Mario

**Comment by jobenvil** [comment]
@vmario89 oh, I'm sorry that you are not aware and thus you spent your time. Anyway, thanks for sharing.

Before download the rpi-version is clearly specified the support channel. 

![Support Channel on Github](https://hiperborea.de/seafile/f/53b7ed10d4ca4356830b/?dl=1)

You have done another workaround. The correct one is to install Pillow again directly like as user `seafile `in the `thirdpart`y directory with the flag `-t` for `target`, if you had 3.6.10 (additionally installed Python 3.6.10 since stretch didn't ship). This is [documented here](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945), since [that](https://github.com/haiwen/seafile-rpi#reporting-issues--github-issues).

Please consider to subscribe to the forum and you will get these news/recommendations on time. 

This new version had many points to consider, therefore I spent a lot of time summarizing the issues that could arise.

**Comment by davigega** [comment]
Hello!
I hope that I'm not doing anything wrong posting on this issue...
I just installed Seafile on a Raspi3b+ Buster from seafile-server-7.1.5-buster-armv7.tar.gz and everything worked flawless, until I run into this problem. I tried both your solution, but none of them seems to work. Is there any update about this issue that I missed.
Thank you!

**Comment by jobenvil** [comment]
@davigega open your own thread on seafile forum

**Comment by davigega** [comment]
thank you for the quick answer. sorry...I will
