### ISSUE TITLE
Error after upgrade from 6.1.2 to 6.2.2

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-rpi#26]
I found this error after upgrading:

./seafile.sh start

[10/06/17 18:13:10] ../common/session.c(132): using config file /home/seafile/JWPfs/conf/ccnet.conf
[10/06/17 18:13:10] ../common/ccnet-db.c(142): Error exec query CREATE UNIQUE INDEX IF NOT EXISTS reference_id_index on EmailUser (reference_id): sqlite3_exec failed: table EmailUser has no column named reference_id.
failed to run "ccnet-server -t"

**Comment by jobenvil** [comment]
Please find more infos [here and do the mentioned workaround](https://forum.seafile.com/t/seafile-server-6-2-0-beta-is-ready-for-testing/3941/30).

**Comment by jhonny-oliveira** [comment]
My bad! I built a script to upgrade automatically, but I left the minor_upgrade script hard coded. I fixed it as soon as I found out.
